### PR TITLE
Logic changes to deal with double power outputs on axles

### PR DESCRIPTION
**Pull request by Dryxen**
should completely deal with gearboxes that are placed incorrectly depowering axles.
edit:  i'm out for the night if something needs to be changed ill get to it in the morning.
edit: I feel axles should have some sort of checks to see if side is input or output so we could simply check it before setting power to 0, but i didnt wanna change the way the internals work to majorly.

### CODE REVIEW

**Comment by DaedalusGame** [comment]
what does this address, exactly? does this make axles stop spinning when they receive two inputs from opposite sides?

**Comment by Dryxen** [comment]
probably easier to load the mod up and check it as its hard to describe but ill try to explain. if you have a gear/mergebox powering a axle and you place a empty box output side next to said axle it completly stops the system on break, since it always sets the adjacent power to 0 . this fixes said issue but doesn't affect normal behavior otherwise.
Edit:if i remeber right i also added sanity checks to gearbox update to make sure things were being unpowered correctly on gearbox or gear removal.
Edit: i still haven't experienced disappearing gears as mentioned in #14 but still looking =P.

**Comment by DaedalusGame** [comment]
I'm not seeing this behavior in dev so i'm not sure i fully understood how to reproduce this
edit: wait i got it, it happens only on one-wide axles

**Comment by Dryxen** [comment]
hmm should just need to hook gear box up to a creative source like normal then stick a axle to one of the gearboxes outputs, then add a second gearbox output side onto the same axle. I actually need to check if sticking a output gearbox onto another gearbox resets its power to 0 since i completly forgot it.

**Comment by Dryxen** [comment]
anything that extends IGearbox sets output side connection to 0 on break.
Edit: ya i check boxes after i finish cooking for the kids, im guessing mergeboxs connected to a output side gearbox will break as well.

**Comment by DaedalusGame** [comment]
this is a bit suspect, it doesn't happen if one of the gearboxes is just a creative power source so something might still be wrong in gearbox code land....

**Comment by Dryxen** [comment]
I'll try to find the exact cause in a bit if you want, i thought it was just due to setting output to 0.

**Comment by DaedalusGame** [comment]
ah i see, it's because creative power sources call updateNeighbor every tick so it automatically fixes itself. this is a bit of a problem but i'd prefer if this could be solved on the axle level possibly

**Comment by Dryxen** [comment]
aye i completly agree with you this was a bandaide fix, as i mentioned above i felt it needed to be handled in the axle but i didnt wanna mess with the ground mechanics of your mod without you giving it a green light. did you want to deal with the mechanic changes yourself?

**Comment by DaedalusGame** [comment]
if you want to have a shot at the axle changes feel free. The code can only get better, really :p

**Comment by Dryxen** [comment]
gotcha ill branch my current and do some overhaul experiments, I also feel that they tile entitys should be abstracted a bit from some some sort of base Tileentity class so the code shared between all the Mystical tile entites can be called without specification things like getPower() and such. how do you feel?

**Comment by DaedalusGame** [comment]
I think abstraction should be fine as long as it's a) not 1-baseclass for everything nightmare carnival and b) not necessary for api implementors

**Comment by Dryxen** [comment]
ya atm we are limited to basic minecraft tileentities on alot of checks it would just be nice to check for mysticaltileentity and then run methods that are already shared between your tileentities like setpower and such

**Comment by Dryxen** [comment]
Going close this until proposed changes are complete. thanks for your attention =P.

**Pull request closed without merging**
